### PR TITLE
Compatibility with Windows 11 with classic taskbar

### PR DESCRIPTION
**Pull request by valinet**
Hi

On Windows 11, it is still possible to enable the classic taskbar using a software like my own [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher). Thus, TaskbarX can still function there, and it does so brilliantly. The only slight issue is that the main taskbar does not get centered. That's because of an oversight in the code: an exception happens in the function  `TaskbarX!TaskbarCenter::GetLocation`, specifically this line:

```
acc.accLocation(rect.left, rect.top, rect.width, rect.height, idChild)
```

The call stack shows that the caller is this line:

```
NewsAndInterestsPos = GetLocation(accessible5, 0)
```

It seems that `accessible5` is `null` (or `Nothing` in VB.NET terms). `accessible5` is basically an interface derived from a handle to the "News and interests" button on the taskbar, as far as I understand. But on Windows 11, there is no such button anymore - that functionality has been replaced by widgets. Thus, the handle is empty and from there an `Accessibility.IAccessible` cannot be obtained (so `TaskbarX!TaskbarCenter::GetLocation` receives a `Nothing`), and from that, `Accessibility.IAccessible::accLocation` cannot obtain the location, naturally.

My naive fix was to check whether `acc` is `Nothing` before calling methods on it. Generally, I think such a sanitization should be in place for that function anyway, you never know when something passes `Nothing` as the first argument, at least the program does not fail, it is safe to assume `Nothing` would return a `RectangleX` with all members set to `0`.

Running with this small fix in place, it then works just fine on Windows 11 as well, no other changes required. I don't know if this is the proper fix, or you prefer to do some checks regarding OS version and decided to create/not create some objects based on that, but this is indeed a quick fix for the problem with no side effects as far as I have noticed and I think it is worth getting merged in the upstream.

Thus, I am proposing the following pull request.

Thank you very much for this wonderful application and I am looking forward to seeing this merged soon.

### CODE REVIEW

**Comment by valinet** [comment]
Thank you. Keep up the good work!

**Comment by ChrisAnd1998** [comment]
@valinet Thank you! Sorry for the late response.. I will merge this ASAP ;)

**Comment by valinet** [comment]
Thank you very much!

And hey - don’t worry about the slight delay - things happen, I perfectly understand it. Keep up the good work!

Thanks

**Comment by XPower7125** [comment]
not working on windows 11
Wanted to center ONLY taskar icons on windows 11 (not start menu...)
I used taskbarx 1.7.3 but it doesn't work.
image

**Comment by XPower7125** [comment]
TaskbarX not working on windows 11
I wanted to center only taskbar icons (not start...)
I used taskbarx 1.7.3.0 but it doesn't work.
image

**Pull request merged**
