### PR TITLE
Added duplicate search notice

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**

### CODE REVIEW

**Review by Mr-Anonymous75 — CHANGES_REQUESTED** [review]
I'd suggest you use "you" instead of "u". Also, remove the "Hi,".

**Comment by yashpalgoyal1304** [comment]
I guess Hi sets the tone to a bit more casual. are u sure about removing that?

**Comment by yashpalgoyal1304** [comment]
have corrected the typo in u and missing apostrophe as well. Waiting for confirmation about removal of hi. Feel free to mark it as ready (i dont know if the maintainers can do that or it's only author who can do it) if no further changes are required.

**Comment by yashpalgoyal1304** [comment]
hi @ChrisAnd1998 umh, so, what does the closure mean??

**Comment by ChrisAnd1998** [comment]
Sorry should not have been closed. Looking into this right now..

**Comment by ChrisAnd1998** [comment]
@yashpalgoyal1304 Thank you! Sorry for the late response on this!
You may noticed all issues got closed. There where so many old, duplicate and already fixed issues that I didn't know what needs fixing anymore. So from here on we start fresh. People can still reopen the issue if the issue still persists after todays update.

**Comment by ChrisAnd1998** [comment]
@yashpalgoyal1304 Also updated #108  ;)

**Comment by yashpalgoyal1304** [comment]
thanks for update, yep, i can understand that. 

- the duplicate issues can be a frustration to deal with....
- i wish i had shared the version i was using in my issues (mostly new feature requests) 😅 but anyways....
- also, since my issues were (radically) new feature requests, i dont think i will feel comfortable reopening those.... 
(uhh, i dont know, am feeling a bit out of senses...)

**Comment by ChrisAnd1998** [comment]
Well all feature requests will be listed here: #870
Still need to clean that up.. But as you can see the list is big.
The problem is that I need all bugs out first before adding new features because new features always come with new bugs. 😅

**Comment by yashpalgoyal1304** [comment]
hi, so, one more question: how did u make that list??
i mean, it cant be made totally manual i guess, so, what app etc did u use to get that list? to automate/ease some part of the process.... i hope this question makes sense

**Comment by ChrisAnd1998** [comment]
@yashpalgoyal1304 Actually I did it all manually XD. If a new one comes I can just add it to the list. That's not to big of a deal but perhaps GitHub has an API for this..

**Pull request merged**
